from __future__ import annotations

import asyncio
import hashlib
import json

import httpx
import pytest

from services.api.app.connect_inmyrnd import (
    InMyRndRuntimeClient,
    RndAuthorityClient,
    RndExecutionError,
    experiment_digest,
)


TOKEN = 'hub-service-test-token-0123456789'
PROJECT_ID = 'rndp_22222222-2222-2222-2222-222222222222'
EXPERIMENT_ID = 'rnde_11111111-1111-1111-1111-111111111111'
AUTH_ID = 'rndauth_' + ('a' * 20)
RECEIPT_ID = 'rndrct_' + ('b' * 20)
DIGEST = f'sha256:{"a" * 64}'


def make_authority_client(handler, *, base_url: str = 'http://127.0.0.1:8787') -> RndAuthorityClient:
    return RndAuthorityClient(
        base_url=base_url,
        hub_service_token=TOKEN,
        timeout_seconds=5,
        transport=httpx.MockTransport(handler),
    )


def make_runtime_client(handler, *, base_url: str = 'http://127.0.0.1:17420') -> InMyRndRuntimeClient:
    return InMyRndRuntimeClient(
        base_url=base_url,
        timeout_seconds=5,
        transport=httpx.MockTransport(handler),
    )


# --- experiment_digest() -- cross-checked against real Node output --------
#
# Reference digests generated by running InMyR&D's real, live, unmodified
# lib/domain.mjs experimentDigest() under Node against the exact fixtures
# below (see this delivery's gen_reference_digests.mjs). This is the
# strongest verification available short of running against InMyR&D itself:
# the actual function, not a re-derivation of the same Python logic, which
# would not catch a shared misunderstanding of the algorithm.

ASCII_EXPERIMENT = {
    'schemaVersion': 1,
    'id': 'rnde_11111111-1111-1111-1111-111111111111',
    'projectId': 'rndp_22222222-2222-2222-2222-222222222222',
    'name': 'Baseline vs variant',
    'hypothesis': 'Variant B improves quality',
    'status': 'ready',
    'mode': 'deterministic-scorecard',
    'weights': {'quality': 0.35, 'cost': 0.2, 'latency': 0.15, 'privacy': 0.15, 'reliability': 0.15},
    'cases': [
        {
            'id': 'case_aaa', 'name': 'Baseline', 'evidenceClass': 'measured',
            'evidenceRef': 'https://example.com/report', 'notes': 'control group',
            'metrics': {'quality': 70, 'cost': 50, 'latency': 60, 'privacy': 80, 'reliability': 90},
        },
        {
            'id': 'case_bbb', 'name': 'Variant B', 'evidenceClass': 'assumption',
            'evidenceRef': '', 'notes': '',
            'metrics': {'quality': 85, 'cost': 40, 'latency': 55, 'privacy': 75, 'reliability': 88},
        },
    ],
    'createdAt': '2026-09-03T00:00:00.000Z',
    'updatedAt': '2026-09-03T00:00:00.000Z',
}
# Non-ASCII: café, em dash, curly quotes, Indonesian text, Japanese, emoji,
# German umlaut/eszett -- the exact class of content this program flagged
# as the load-bearing risk in a naive Python port (json.dumps's default
# ensure_ascii=True silently diverges from JS's JSON.stringify here).
NON_ASCII_EXPERIMENT = {
    'schemaVersion': 1,
    'id': 'rnde_33333333-3333-3333-3333-333333333333',
    'projectId': 'rndp_44444444-4444-4444-4444-444444444444',
    'name': 'Café — “Kualitas” percobaan',
    'hypothesis': 'Peningkatan kualitas untuk pengguna Indonesia — targetnya 20% lebih baik',
    'status': 'ready',
    'mode': 'deterministic-scorecard',
    'weights': {'quality': 0.5, 'cost': 0.2, 'latency': 0.1, 'privacy': 0.1, 'reliability': 0.1},
    'cases': [
        {
            'id': 'case_ccc', 'name': 'Kontrol', 'evidenceClass': 'real_world',
            'evidenceRef': 'naïve baseline — data lapangan',
            'notes': 'Catatan: “baik” tapi belum sempurna — perlu ditinjau ulang',
            'metrics': {'quality': 60, 'cost': 45, 'latency': 50, 'privacy': 70, 'reliability': 65},
        },
        {
            'id': 'case_ddd', 'name': 'Ekspérimen Ω', 'evidenceClass': 'simulated',
            'evidenceRef': '日本語のメモ', 'notes': 'emoji test 🚀 and ñ, ü, ß',
            'metrics': {'quality': 90, 'cost': 30, 'latency': 40, 'privacy': 85, 'reliability': 95},
        },
    ],
    'createdAt': '2026-09-03T00:00:00.000Z',
    'updatedAt': '2026-09-03T00:00:00.000Z',
}
NODE_REFERENCE_ASCII = 'sha256:b3b3f02c9746dbe355a3e42862fb63aae2b7eb45522a9e56fe26648b0d184e57'
NODE_REFERENCE_NON_ASCII = 'sha256:0762504613321e4430f5c3319d907de409bc4a3d8a5e6044b1a30d97c6ebc29f'


def test_experiment_digest_matches_real_node_output_ascii() -> None:
    assert experiment_digest(ASCII_EXPERIMENT) == NODE_REFERENCE_ASCII


def test_experiment_digest_matches_real_node_output_non_ascii() -> None:
    assert experiment_digest(NON_ASCII_EXPERIMENT) == NODE_REFERENCE_NON_ASCII


def test_experiment_digest_ensure_ascii_true_would_have_diverged() -> None:
    # Guards against a regression back to the exact bug this program
    # flagged during Piece 3 discovery: json.dumps's default
    # ensure_ascii=True silently produces a DIFFERENT digest than
    # InMyR&D's real one whenever a field has a non-ASCII character. If
    # this assertion ever fails, experiment_digest() has regressed into
    # that bug.
    exp = NON_ASCII_EXPERIMENT
    keys = ('quality', 'cost', 'latency', 'privacy', 'reliability')
    payload = {
        'schemaVersion': exp['schemaVersion'], 'projectId': exp['projectId'], 'name': exp['name'],
        'hypothesis': exp['hypothesis'], 'mode': exp['mode'],
        'weights': {k: exp['weights'][k] for k in keys},
        'cases': [{
            'name': c['name'], 'evidenceClass': c['evidenceClass'], 'evidenceRef': c['evidenceRef'],
            'notes': c['notes'], 'metrics': {k: c['metrics'][k] for k in keys},
        } for c in exp['cases']],
    }
    wrong = f'sha256:{hashlib.sha256(json.dumps(payload, separators=(",", ":"), ensure_ascii=True).encode()).hexdigest()}'
    assert wrong != NODE_REFERENCE_NON_ASCII
    assert experiment_digest(exp) == NODE_REFERENCE_NON_ASCII


def test_experiment_digest_stable_under_input_key_reordering() -> None:
    # A dict with the same content but different insertion order must
    # produce the same digest -- experiment_digest() rebuilds its own
    # payload dict in a fixed key order rather than trusting the input's.
    reordered = dict(reversed(list(ASCII_EXPERIMENT.items())))
    reordered['weights'] = dict(reversed(list(ASCII_EXPERIMENT['weights'].items())))
    assert experiment_digest(reordered) == experiment_digest(ASCII_EXPERIMENT)


def test_experiment_digest_ignores_case_id_and_other_extra_fields() -> None:
    # Mirrors the real function's destructuring map ({ name, evidenceClass,
    # evidenceRef, notes, metrics }) -- a case's own `id` (and any other
    # extra field) must not affect the digest.
    without_case_ids = json.loads(json.dumps(ASCII_EXPERIMENT))
    for case in without_case_ids['cases']:
        del case['id']
    assert experiment_digest(without_case_ids) == NODE_REFERENCE_ASCII


def test_experiment_digest_changes_when_a_metric_changes() -> None:
    changed = json.loads(json.dumps(ASCII_EXPERIMENT))
    changed['cases'][0]['metrics']['quality'] = 71
    assert experiment_digest(changed) != NODE_REFERENCE_ASCII


# --- loopback URL validation (both clients) --------------------------------

def test_authority_client_accepts_only_explicit_loopback_http_origins() -> None:
    handler = lambda request: httpx.Response(200, json={'ok': True})
    assert make_authority_client(handler).base_url == 'http://127.0.0.1:8787'
    for invalid in (
        'http://localhost:8787',
        'https://127.0.0.1:8787',
        'http://127.0.0.1',
        'http://user:pass@127.0.0.1:8787',
        'http://127.0.0.1:8787/api',
    ):
        with pytest.raises(ValueError):
            make_authority_client(handler, base_url=invalid)


def test_runtime_client_accepts_only_explicit_loopback_http_origins() -> None:
    handler = lambda request: httpx.Response(200, json=[])
    assert make_runtime_client(handler).base_url == 'http://127.0.0.1:17420'
    with pytest.raises(ValueError):
        make_runtime_client(handler, base_url='https://127.0.0.1:17420')


def test_runtime_client_never_sends_an_authorization_header() -> None:
    captured: dict = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured['authorization'] = request.headers.get('authorization')
        return httpx.Response(200, json=[])

    async def run() -> list:
        return await make_runtime_client(handler).list_experiments()

    asyncio.run(run())
    assert captured['authorization'] is None


# --- RndAuthorityClient: authorize/intent/record forward exact bodies -----

def test_authorize_forwards_exact_field_shape() -> None:
    captured: dict = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured['path'] = request.url.path
        captured['authorization'] = request.headers.get('authorization')
        captured['body'] = json.loads(request.content)
        return httpx.Response(200, json={
            'schemaVersion': '1.0.0', 'authorized': True, 'authorizationId': AUTH_ID,
            'actorId': 'agent:inmyai', 'providerId': 'inmyrnd', 'actionId': 'experiment.run',
            'riskClass': 'R1', 'mode': 'execute', 'projectId': PROJECT_ID,
            'experimentId': EXPERIMENT_ID, 'experimentDigest': DIGEST,
            'idempotencyKey': 'idem_abcdefghijklmnop', 'expiresAt': '2026-09-03T00:06:00.000Z',
        })

    async def run() -> dict:
        return await make_authority_client(handler).authorize(
            workflow_run_id='run_abcdefghijklmnop',
            delegation_id='dlg_abcdefghijklmnop',
            project_id=PROJECT_ID,
            experiment_id=EXPERIMENT_ID,
            experiment_digest=DIGEST,
            idempotency_key='idem_abcdefghijklmnop',
        )

    payload = asyncio.run(run())
    assert payload['authorized'] is True
    assert captured['path'] == '/api/rnd-execution/r1/authorize'
    assert captured['authorization'] == f'Bearer {TOKEN}'
    assert captured['body'] == {
        'workflowRunId': 'run_abcdefghijklmnop',
        'delegationId': 'dlg_abcdefghijklmnop',
        'providerId': 'inmyrnd',
        'actionId': 'experiment.run',
        'projectId': PROJECT_ID,
        'experimentId': EXPERIMENT_ID,
        'experimentDigest': DIGEST,
        'idempotencyKey': 'idem_abcdefghijklmnop',
    }


def test_authorize_rejects_malformed_project_id_before_any_request() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError('should not be called')

    async def run() -> None:
        await make_authority_client(handler).authorize(
            workflow_run_id='run_abcdefghijklmnop',
            delegation_id='dlg_abcdefghijklmnop',
            project_id='not-a-real-project-id',
            experiment_id=EXPERIMENT_ID,
            experiment_digest=DIGEST,
            idempotency_key='idem_abcdefghijklmnop',
        )

    with pytest.raises(ValueError):
        asyncio.run(run())


def test_authorize_rejects_experiment_id_wearing_project_prefix() -> None:
    # A project_id passed where an experiment_id belongs (or vice versa)
    # must be rejected locally, before ever reaching Hub -- the rndp_/rnde_
    # prefixes are not interchangeable even though the rest of the shape
    # (UUID) is identical.
    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError('should not be called')

    async def run() -> None:
        await make_authority_client(handler).authorize(
            workflow_run_id='run_abcdefghijklmnop',
            delegation_id='dlg_abcdefghijklmnop',
            project_id=PROJECT_ID,
            experiment_id=PROJECT_ID,  # wrong prefix for an experiment_id
            experiment_digest=DIGEST,
            idempotency_key='idem_abcdefghijklmnop',
        )

    with pytest.raises(ValueError):
        asyncio.run(run())


def test_record_intent_forwards_exact_field_shape() -> None:
    captured: dict = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured['path'] = request.url.path
        captured['body'] = json.loads(request.content)
        return httpx.Response(200, json={
            'schemaVersion': '1.0.0', 'intentId': 'rndhubi_x',
            'authorizationId': AUTH_ID, 'startedAt': '2026-09-03T00:00:01.000Z',
        })

    async def run() -> dict:
        return await make_authority_client(handler).record_intent(
            workflow_run_id='run_abcdefghijklmnop',
            delegation_id='dlg_abcdefghijklmnop',
            authorization_id=AUTH_ID,
            idempotency_key='idem_abcdefghijklmnop',
            project_id=PROJECT_ID,
            experiment_id=EXPERIMENT_ID,
            experiment_digest=DIGEST,
            started_at='2026-09-03T00:00:01.000Z',
        )

    payload = asyncio.run(run())
    assert payload['intentId'] == 'rndhubi_x'
    assert captured['path'] == '/api/rnd-execution/r1/intent'
    assert captured['body'] == {
        'workflowRunId': 'run_abcdefghijklmnop',
        'delegationId': 'dlg_abcdefghijklmnop',
        'authorizationId': AUTH_ID,
        'idempotencyKey': 'idem_abcdefghijklmnop',
        'providerId': 'inmyrnd',
        'actionId': 'experiment.run',
        'projectId': PROJECT_ID,
        'experimentId': EXPERIMENT_ID,
        'experimentDigest': DIGEST,
        'startedAt': '2026-09-03T00:00:01.000Z',
    }


def test_record_execution_validates_outcome_before_any_request() -> None:
    # Unlike Sandbox's three-value outcome set, rnd-execution/r1 only
    # allows completed/failed -- confirmed against the real, merged
    # rnd-execution-r1-authority.mjs (ALLOWED_OUTCOMES has no 'timed_out').
    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError('should not be called')

    receipt = {
        'schemaVersion': '1.0.0', 'receiptId': RECEIPT_ID, 'authorizationId': AUTH_ID,
        'outcome': 'timed_out',
    }

    async def run() -> None:
        await make_authority_client(handler).record_execution(
            workflow_run_id='run_abcdefghijklmnop',
            delegation_id='dlg_abcdefghijklmnop',
            authorization_id=AUTH_ID,
            idempotency_key='idem_abcdefghijklmnop',
            project_id=PROJECT_ID,
            experiment_id=EXPERIMENT_ID,
            experiment_digest=DIGEST,
            recorded_at='2026-09-03T00:00:02.000Z',
            executor_receipt=receipt,
        )

    with pytest.raises(ValueError):
        asyncio.run(run())


def test_record_execution_forwards_receipt_unmodified_on_success() -> None:
    captured: dict = {}
    receipt = {
        'schemaVersion': '1.0.0', 'receiptId': RECEIPT_ID, 'authorizationId': AUTH_ID,
        'providerId': 'inmyrnd', 'actionId': 'experiment.run', 'projectId': PROJECT_ID,
        'experimentId': EXPERIMENT_ID, 'experimentDigest': DIGEST,
        'mode': 'rnd-execution', 'riskClass': 'R1', 'idempotencyKey': 'idem_abcdefghijklmnop',
        'executedAt': '2026-09-03T00:00:02.000Z', 'outcome': 'completed',
        'outputs': {'algorithmVersion': 'deterministic-scorecard-v1', 'rowCount': 2},
    }

    def handler(request: httpx.Request) -> httpx.Response:
        captured['path'] = request.url.path
        captured['body'] = json.loads(request.content)
        return httpx.Response(200, json={'schemaVersion': '1.0.0', 'receiptId': 'rndhubr_x', 'outcome': 'completed'})

    async def run() -> dict:
        return await make_authority_client(handler).record_execution(
            workflow_run_id='run_abcdefghijklmnop',
            delegation_id='dlg_abcdefghijklmnop',
            authorization_id=AUTH_ID,
            idempotency_key='idem_abcdefghijklmnop',
            project_id=PROJECT_ID,
            experiment_id=EXPERIMENT_ID,
            experiment_digest=DIGEST,
            recorded_at='2026-09-03T00:00:02.000Z',
            executor_receipt=receipt,
        )

    payload = asyncio.run(run())
    assert payload['receiptId'] == 'rndhubr_x'
    assert captured['path'] == '/api/rnd-execution/r1/record'
    assert captured['body']['executorReceipt'] == receipt


def test_status_is_a_bare_get_with_no_body() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.method == 'GET'
        assert request.url.path == '/api/rnd-execution/r1/status'
        return httpx.Response(200, json={
            'schemaVersion': '1.0.0', 'executionEnabled': True, 'provider': 'inmyrnd',
            'actions': ['experiment.run'], 'riskClass': 'R1', 'mode': 'execute',
            'automaticRoutingAllowed': False, 'silentFallbackAllowed': False,
            'authorizations': 0, 'receipts': 0, 'intents': 0,
        })

    async def run() -> dict:
        return await make_authority_client(handler).status()

    payload = asyncio.run(run())
    assert payload['provider'] == 'inmyrnd'


# --- Hub-side errors never set execution_may_have_run ----------------------

def test_authority_client_errors_never_set_execution_may_have_run() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(409, json={'error': 'not allowed', 'code': 'R1_RND_PROVIDER_NOT_ALLOWED'})

    async def run() -> None:
        await make_authority_client(handler).authorize(
            workflow_run_id='run_abcdefghijklmnop',
            delegation_id='dlg_abcdefghijklmnop',
            project_id=PROJECT_ID,
            experiment_id=EXPERIMENT_ID,
            experiment_digest=DIGEST,
            idempotency_key='idem_abcdefghijklmnop',
        )

    with pytest.raises(RndExecutionError) as excinfo:
        asyncio.run(run())
    assert excinfo.value.status_code == 409
    assert excinfo.value.code == 'R1_RND_PROVIDER_NOT_ALLOWED'
    assert excinfo.value.execution_may_have_run is False


def test_authority_client_maps_network_failure_to_unavailable_error() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise httpx.ConnectError('refused', request=request)

    async def run() -> None:
        await make_authority_client(handler).status()

    with pytest.raises(RndExecutionError, match='unavailable'):
        asyncio.run(run())


# --- InMyRndRuntimeClient: list_experiments/run_experiment -----------------

def test_list_experiments_parses_the_full_array_and_filters_client_side() -> None:
    # InMyR&D has no single-experiment GET route (confirmed against the
    # real, live server.mjs) -- callers must fetch the full list and find
    # the experiment by id themselves.
    experiments = [
        {'id': EXPERIMENT_ID, 'projectId': PROJECT_ID, 'name': 'x'},
        {'id': 'rnde_99999999-9999-9999-9999-999999999999', 'projectId': PROJECT_ID, 'name': 'y'},
    ]

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.method == 'GET'
        assert request.url.path == '/api/experiments'
        return httpx.Response(200, json=experiments)

    async def run() -> list:
        return await make_runtime_client(handler).list_experiments()

    payload = asyncio.run(run())
    assert payload == experiments
    found = next(e for e in payload if e['id'] == EXPERIMENT_ID)
    assert found['name'] == 'x'


def test_list_experiments_rejects_a_non_array_response() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, json={'not': 'an array'})

    async def run() -> None:
        await make_runtime_client(handler).list_experiments()

    with pytest.raises(RndExecutionError, match='array'):
        asyncio.run(run())


def test_list_experiments_failure_is_never_flagged_as_ambiguous() -> None:
    # A pure read: even a clean 5xx here carries no real-side-effect risk.
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(500, json={'error': 'boom'})

    async def run() -> None:
        await make_runtime_client(handler).list_experiments()

    with pytest.raises(RndExecutionError) as excinfo:
        asyncio.run(run())
    assert excinfo.value.execution_may_have_run is False


def test_run_experiment_reads_no_request_body_and_forwards_the_full_run_object() -> None:
    captured: dict = {}
    run_object = {
        'schemaVersion': 1, 'id': 'rndr_x', 'experimentId': EXPERIMENT_ID, 'projectId': PROJECT_ID,
        'experimentDigest': DIGEST, 'algorithmVersion': 'deterministic-scorecard-v1',
        'mode': 'deterministic-scorecard', 'weights': {}, 'evidenceSummary': {}, 'rows': [],
        'recommendation': None, 'disclaimer': 'x', 'createdAt': '2026-09-03T00:00:02.000Z',
    }

    def handler(request: httpx.Request) -> httpx.Response:
        captured['method'] = request.method
        captured['path'] = request.url.path
        captured['body'] = request.content
        return httpx.Response(201, json=run_object)

    async def run() -> dict:
        return await make_runtime_client(handler).run_experiment(EXPERIMENT_ID)

    payload = asyncio.run(run())
    assert payload == run_object
    assert captured['method'] == 'POST'
    assert captured['path'] == f'/api/experiments/{EXPERIMENT_ID}/run'
    assert json.loads(captured['body']) == {}


def test_run_experiment_flags_execution_may_have_run_when_a_2xx_body_is_truncated() -> None:
    # The genuinely ambiguous case: InMyR&D answered 201 (it believes the
    # run was recorded) but the body we received is not valid JSON -- e.g.
    # the connection dropped mid-response. A run record may already have
    # been appended and the experiment's status already flipped to
    # 'evaluated'; this must be flagged so a caller does not blindly retry
    # under a new idempotency key.
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(201, content=b'{"id": "rndr_truncated', headers={'content-type': 'application/json'})

    async def run() -> None:
        await make_runtime_client(handler).run_experiment(EXPERIMENT_ID)

    with pytest.raises(RndExecutionError) as excinfo:
        asyncio.run(run())
    assert excinfo.value.execution_may_have_run is True


def test_run_experiment_clean_404_is_not_flagged_as_ambiguous() -> None:
    # A clean non-2xx response (InMyR&D's own handler ran and reported the
    # experiment does not exist) is a definitive "it did not happen"
    # signal -- no run was appended, safe to retry as-is.
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(404, json={'error': 'experiment not found'})

    async def run() -> None:
        await make_runtime_client(handler).run_experiment(EXPERIMENT_ID)

    with pytest.raises(RndExecutionError) as excinfo:
        asyncio.run(run())
    assert excinfo.value.execution_may_have_run is False


def test_run_experiment_rejects_malformed_experiment_id_before_any_request() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError('should not be called')

    async def run() -> None:
        await make_runtime_client(handler).run_experiment('not-a-real-id')

    with pytest.raises(ValueError):
        asyncio.run(run())


# --- source hygiene ---------------------------------------------------------

def test_connect_inmyrnd_source_never_hardcodes_a_secret() -> None:
    from pathlib import Path
    source = Path('services/api/app/connect_inmyrnd.py').read_text(encoding='utf-8')
    assert 'openrouter.ai' not in source.lower()
    assert 'api.openai.com' not in source.lower()
    assert 'api_key' not in source.lower()
    assert 'access_token' not in source.lower()
