from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import httpx

from .config import settings
from .services import get_project


def replace_placeholders(value: Any, replacements: dict[str, str | int]) -> Any:
    if isinstance(value, dict):
        return {key: replace_placeholders(item, replacements) for key, item in value.items()}
    if isinstance(value, list):
        return [replace_placeholders(item, replacements) for item in value]
    if isinstance(value, str):
        result = value
        for key, replacement in replacements.items():
            result = result.replace(f'{{{{{key}}}}}', str(replacement))
        return result
    return value


def find_first_image(history: dict) -> dict | None:
    outputs = history.get('outputs') or {}
    for output in outputs.values():
        for image in output.get('images') or []:
            if image.get('filename'):
                return image
    return None


async def generate_with_comfyui(
    project_id: int,
    prompt: str,
    negative_prompt: str,
    width: int,
    height: int,
    steps: int,
    seed: int,
) -> dict:
    workflow_path = Path(settings.comfyui_workflow_path).expanduser()
    if not settings.comfyui_workflow_path or not workflow_path.exists():
        raise ValueError('COMFYUI_WORKFLOW_PATH does not point to an existing workflow JSON file.')

    workflow = json.loads(workflow_path.read_text(encoding='utf-8'))
    workflow = replace_placeholders(workflow, {
        'PROMPT': prompt,
        'NEGATIVE_PROMPT': negative_prompt,
        'WIDTH': width,
        'HEIGHT': height,
        'STEPS': steps,
        'SEED': seed,
    })

    async with httpx.AsyncClient(timeout=30) as client:
        queued = await client.post(
            f'{settings.comfyui_base_url}/prompt',
            json={'prompt': workflow, 'client_id': 'inmyai-local'}
        )
        queued.raise_for_status()
        prompt_id = queued.json().get('prompt_id')
        if not prompt_id:
            raise RuntimeError('ComfyUI did not return a prompt_id.')

        history_item: dict | None = None
        for _ in range(300):
            response = await client.get(f'{settings.comfyui_base_url}/history/{prompt_id}')
            response.raise_for_status()
            payload = response.json()
            if prompt_id in payload:
                history_item = payload[prompt_id]
                if history_item.get('status', {}).get('status_str') == 'error':
                    raise RuntimeError('ComfyUI reported an execution error.')
                image = find_first_image(history_item)
                if image:
                    break
            await asyncio.sleep(1)
        else:
            raise TimeoutError('Timed out waiting for ComfyUI output.')

        image = find_first_image(history_item or {})
        if not image:
            raise RuntimeError('ComfyUI completed without an image output.')
        view = await client.get(
            f'{settings.comfyui_base_url}/view',
            params={
                'filename': image['filename'],
                'subfolder': image.get('subfolder', ''),
                'type': image.get('type', 'output')
            }
        )
        view.raise_for_status()

    project = get_project(project_id)
    output_dir = Path(project['path']) / '.inmyai' / 'generated'
    output_dir.mkdir(parents=True, exist_ok=True)
    suffix = Path(image['filename']).suffix or '.png'
    output = output_dir / f'comfyui-{prompt_id}{suffix}'
    output.write_bytes(view.content)
    return {
        'provider': 'comfyui',
        'path': str(output),
        'relative_path': output.relative_to(Path(project['path'])).as_posix(),
        'seed': seed,
        'prompt_id': prompt_id,
        'notice': 'Generated by the user-configured local ComfyUI workflow.'
    }
