const state={view:'agents',projects:[],projectId:null,agents:[],tasks:[],files:[],hardware:null,selected:null,notice:''};
const api=async(path,init={})=>{const r=await fetch(path,{...init,headers:{'content-type':'application/json',...(init.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||`HTTP ${r.status}`);return b};
const el=(tag,attrs={},children=[])=>{const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?n.className=v:k.startsWith('on')?n.addEventListener(k.slice(2).toLowerCase(),v):n.setAttribute(k,v));for(const c of [].concat(children))n.append(c?.nodeType?c:document.createTextNode(c??''));return n};
async function load(){try{const [projects,hardware]=await Promise.all([api('/api/projects'),api('/api/hardware')]);state.projects=projects;state.hardware=hardware;state.projectId=state.projectId||projects[0]?.id||null;if(state.projectId)await loadProject();render()}catch(e){state.notice=e.message;render()}}
async function loadProject(){const id=state.projectId;[state.agents,state.tasks,state.files]=await Promise.all([api(`/api/projects/${id}/agents`),api(`/api/projects/${id}/tasks`),api(`/api/projects/${id}/files`)])}
async function indexProject(){try{state.notice='Indexing…';render();const r=await api(`/api/projects/${state.projectId}/index`,{method:'POST'});state.notice=`Index complete: ${r.indexed} updated, ${r.unchanged} unchanged, ${r.errors.length} errors.`;await loadProject();render()}catch(e){state.notice=e.message;render()}}
async function createProject(){const name=prompt('Project name');const path=prompt('Absolute folder path allowed by InMyAI');if(!name||!path)return;try{await api('/api/projects',{method:'POST',body:JSON.stringify({name,path})});await load()}catch(e){state.notice=e.message;render()}}
async function runTask(){const text=document.querySelector('#instruction')?.value?.trim();if(!text)return;try{state.notice='Running agent workflow…';render();const t=await api('/api/tasks',{method:'POST',body:JSON.stringify({project_id:state.projectId,title:text.slice(0,80),instruction:text,provider:'auto'})});state.selected=await api(`/api/tasks/${t.id}/run`,{method:'POST'});await loadProject();state.notice='Agent workflow completed and checkpointed.';render()}catch(e){state.notice=e.message;render()}}
async function openTask(id){state.selected=await api(`/api/tasks/${id}`);render()}
function sidebar(){return el('aside',{class:'sidebar'},[el('div',{class:'brand'},['InMyAI',el('small',{},['Local-first agent workspace'])]),el('div',{class:'nav'},[['agents','Agents'],['files','Files'],['knowledge','Knowledge'],['studio','Studio']].map(([id,label])=>el('button',{class:state.view===id?'active':'',onclick:()=>{state.view=id;render()}},[label]))),el('button',{class:'button secondary',onclick:createProject},['Add project'])])}
function top(){const p=state.projects.find(x=>x.id===state.projectId);return el('div',{class:'top'},[el('div',{},[el('h1',{},[state.view[0].toUpperCase()+state.view.slice(1)]),el('p',{},[p?p.name:'Register a local folder to begin'])]),el('div',{},[el('button',{class:'button secondary',onclick:indexProject,disabled:!p},['Index project'])])])}
function agentsView(){const cards=el('div',{class:'agents'},state.agents.map(a=>el('article',{class:'agent'},[el('strong',{},[a.name]),el('p',{},[a.role]),el('div',{class:'status'},[el('span',{class:`dot ${a.status==='working'?'working':''}`}),`${a.status} · ${a.provider}/${a.model}`])])));const comp=el('div',{class:'composer'},[el('textarea',{id:'instruction',rows:'4'},['Read the project context and produce a grounded implementation note.']),el('button',{class:'button primary',onclick:runTask},['Run agent workflow'])]);const history=el('div',{class:'list'},state.tasks.map(t=>el('button',{class:'row',onclick:()=>openTask(t.id)},[el('span',{},[t.title]),el('small',{},[t.status])])));const panels=[el('section',{class:'panel span8'},[el('h2',{},['Logical agents']),el('p',{},['Multiple agents share one canonical context. One heavy local model runs at a time.']),cards,comp]),el('section',{class:'panel span4'},[el('h2',{},['Task history']),el('p',{},['Durable checkpoints and status.']),history])];if(state.selected){panels.push(el('section',{class:'panel'},[el('h2',{},[state.selected.task.title]),el('p',{},[`Status: ${state.selected.task.status}`]),el('div',{class:'timeline'},state.selected.events.map(e=>el('div',{class:'event'},[el('i'),el('div',{},[el('strong',{},[e.state.replaceAll('_',' ')]),el('div',{},[e.message]),el('small',{},[new Date(e.created_at).toLocaleString()])])])),state.selected.task.result_text?el('pre',{},[state.selected.task.result_text]):'']))}return el('div',{class:'grid'},panels)}
function filesView(){return el('div',{class:'grid'},[el('section',{class:'panel span8'},[el('h2',{},['Indexed files']),el('p',{},['Text, code, PDF, DOCX, XLSX, and PPTX parsers.']),el('div',{class:'files'},state.files.map(f=>el('div',{class:'file'},[`${f.relative_path} · ${f.extension} · ${Math.round(f.size_bytes/1024)} KB`])))]),el('section',{class:'panel span4'},[el('h2',{},['Scanner rules']),el('p',{},['Hash-based incremental indexing skips unchanged files and excluded build folders.'])])])}
function knowledgeView(){return el('div',{class:'grid'},[el('section',{class:'panel span8'},[el('h2',{},['Context kernel']),el('p',{},['Canonical decisions, memories, conversation history, file citations, and task checkpoints are stored outside every model.'])]),el('section',{class:'panel span4'},[el('h2',{},['Hardware']),state.hardware?el('div',{},[el('div',{class:'metric'},['Profile',state.hardware.profile]),el('div',{class:'metric'},['RAM free',`${state.hardware.ram.available_gb} GB`]),el('div',{class:'metric'},['Max heavy models','1'])]):''])])}
function studioView(){return el('div',{class:'grid'},[el('section',{class:'panel'},[el('h2',{},['OCR and media providers']),el('p',{},['PDF text extraction and Tesseract are built in. Unlimited-OCR and image generation are isolated optional providers because they require much more memory and separate dependencies.'])])])}
function render(){const app=document.querySelector('#app');app.replaceChildren(el('div',{class:'shell'},[sidebar(),el('main',{class:'main'},[top(),state.notice?el('div',{class:'notice'},[state.notice]):'',!state.projectId?el('section',{class:'panel'},[el('h2',{},['No project registered']),el('p',{},['Add an allowed local folder.'])]):state.view==='agents'?agentsView():state.view==='files'?filesView():state.view==='knowledge'?knowledgeView():studioView()])]))}
load();
